// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package proxy.rmi.simple;

public final class MyRemoteImpl_Stub
    extends java.rmi.server.RemoteStub
    implements proxy.rmi.simple.MyRemote, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_sayHello_0;
    
    static {
	try {
	    $method_sayHello_0 = proxy.rmi.simple.MyRemote.class.getMethod("sayHello", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MyRemoteImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of sayHello()
    public java.lang.String sayHello()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_0, null, 6043973830760146143L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
